export default {
	PRIMARY_COLOR: '#00A981',
	SECONDARY_COLOR: '#A5B1C2',
	DARK_GRAY: '#545B63',
	LIGHT_COLOR: '#ffffff',
	LIGHT_GREEN: '#CCEEE6',
	MUTED_COLOR: '#E8EBEF',
	DULL_WHITE: 'rgba(255, 255, 255, 0.5)',
	RED_COLOR: '#D0152B',
	FONT_SIZE_SMALL: 10,
	FONT_SIZE_DEFAULT: 12,
	FONT_SIZE_MEDIUM: 16,
	FONT_SIZE_LARGE: 20,
	FONT_WEIGHT_LIGHT: '200',
	FONT_WEIGHT_MEDIUM: '500',
	FONT_WEIGHT_BOLD: '700',
	DEFAULT_FONT: 'Montserrat-Regular',
	THIN_FONT: 'Montserrat-Thin',
	LIGHT_FONT: 'Montserrat-Light',
	MEDIUM_FONT: 'Montserrat-Medium',
	SEMIBOLD_FONT: 'Montserrat-SemiBold',
	EXTRABOLD_FONT: 'Montserrat-ExtraBold',
	BOLD_FONT: 'Montserrat-Bold',
	ITALIC_FONT: 'Montserrat-MediumItalic',
	BOLD_ITALIC_FONT: 'Montserrat-BoldItalic',
};
