export default {
	PRIMARY_BLUE: '#0C697D',
	SECONDARY_BLUE: '#267F90',
	DARK_BLUE: '#343B67',
	LIGHT_COLOR: '#ffffff',
	MUTED_COLOR: '#89B9C3',
	DULL_WHITE: 'rgba(255, 255, 255, 0.5)',
	PRIMARY_GREEN: '#169C88',
	SECONDARY_GREEN: '#1EC1A8',
	RED_COLOR: '#D0152B',
	FONT_SIZE_SMALL: 10,
	FONT_SIZE_DEFAULT: 12,
	FONT_SIZE_MEDIUM: 16,
	FONT_SIZE_LARGE: 20,
	FONT_WEIGHT_LIGHT: '200',
	FONT_WEIGHT_MEDIUM: '500',
	FONT_WEIGHT_BOLD: '700',
	DEFAULT_FONT: 'Montserrat-Regular',
	THIN_FONT: 'Montserrat-Thin',
	LIGHT_FONT: 'Montserrat-Light',
	MEDIUM_FONT: 'Montserrat-Medium',
	SEMIBOLD_FONT: 'Montserrat-SemiBold',
	EXTRABOLD_FONT: 'Montserrat-ExtraBold',
	BOLD_FONT: 'Montserrat-Bold',
	ITALIC_FONT: 'Montserrat-MediumItalic',
	BOLD_ITALIC_FONT: 'Montserrat-BoldItalic',
};
