//Authentication
export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
//FEEDS
export const FEEDS_SUCCESS = 'FEEDS_SUCCESS';
//Logout
export const LOGOUT_CLEAR_STORE = 'LOGOUT_CLEAR_STORE';
